### ISSUE TITLE
Angular 2 ?

### ISSUE THREAD

**Issue by patlegris** [jonathaningram/angular-cssmodules-example-app#2]
Hi, do you think we can update easily your work with andular 2 ?

TU

**Comment by jonathaningram** [comment]
Hi @patlegris I haven't looking into Angular 2 yet so not sure. I think this repo should stay for Angular 1 though as I'm sure v1 is not going anywhere anytime soon! There'd be room for an `angular2-cssmodules-example-app` version of this though, and may already be some out in the wild. Thanks, Jon.
