### ISSUE TITLE
import bootstrap globally

### ISSUE THREAD

**Issue by matiishyn** [jonathaningram/angular-cssmodules-example-app#3]
Hi Jonathan. Thank you for a great example. I'm currently trying the same - enable CSS modules on Angular (es6+webpack) application. But I have one question, if you know this please help me.

**Is it possible to import Bootstrap and make it global?**

As I can see you are using Bootstrap classes like this: `ng-class="styles['text-center']"`. But I'd like to leave Bootstrap classes globally and all others as modules:

``` html
<p ng-class="styles['my-module-class']" class="text-center">
```

Ivan

**Comment by jonathaningram** [comment]
@matiishyn I think you should be able to use a webpack loader to exclude a certain file from being processed into CSS modules.

E.g. in index.js

```
import 'bootstrap/whatever/the/path/to/bootstrap.css';
```

Then in your webpack.config.js just make sure that the loader that is processing ".css" files with CSS modules excludes "bootstrap.css". I think that should work.

**Comment by jonathaningram** [comment]
Closing. Feel free to reopen if you need.
